/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const PurchaseIndexLazyImport = createFileRoute('/purchase/')()
const PlatformCriteriaIndexLazyImport = createFileRoute('/platform/criteria/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const PurchaseIndexLazyRoute = PurchaseIndexLazyImport.update({
  path: '/purchase/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/purchase/index.lazy').then((d) => d.Route),
)

const PlatformCriteriaIndexLazyRoute = PlatformCriteriaIndexLazyImport.update({
  path: '/platform/criteria/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/platform/criteria/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/purchase/': {
      preLoaderRoute: typeof PurchaseIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/platform/criteria/': {
      preLoaderRoute: typeof PlatformCriteriaIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  PurchaseIndexLazyRoute,
  PlatformCriteriaIndexLazyRoute,
])

/* prettier-ignore-end */
