image: php:8.3

cache:
  paths:
    - app/vendor/
    - app/node_modules/
    - tools/**/vendor

variables:
  SYMFONY_DEPRECATIONS_HELPER: weak

before_script: &before_script
  - cd app

stages:
  - build
  - qa
  - test
  - deploy

build:
  stage: build
  script:
    - apt-get update
    - apt-get install -y unzip
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install --no-interaction
  artifacts:
    paths:
      - app/vendor/
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

build-qa:
  stage: build
  script:
    - apt-get update
    - apt-get install -y unzip
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - |
      cd ../tools
      for tool in "ecs" "rector" "phpstan" "ecs"; do
        cd $tool
        composer install --no-interaction
        cd ..
      done
      cd ../app
  artifacts:
    paths:
      - tools/**/vendor
      - /usr/local/bin/**
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

qa-ecs:
  stage: qa
  script:
    - ../tools/ecs/vendor/bin/ecs check --clear-cache
  needs: [ "build" ]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - changes:
        - app/modules/**
        - app/src/**
        - app/tests/**

qa-rector:
  stage: qa
  script:
    - ../tools/rector/vendor/bin/rector process --clear-cache
  needs: [ "build" ]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - changes:
        - app/modules/**
        - app/src/**
        - app/tests/**

qa-phpstan:
  stage: qa
  script:
    - ../tools/phpstan/vendor/bin/phpstan analyse src/ modules/*/src -l 1
  needs: [ "build" ]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - changes:
        - app/modules/**
        - app/src/**
        - app/tests/**

test:
  stage: test
  variables:
    XDEBUG_MODE: coverage
    DATABASE_URL: 'sqlite:///%kernel.project_dir%/var/data.db'
  before_script:
    - cd app
    - apt-get update
    - apt-get install -y sqlite3
    - pecl install xdebug && docker-php-ext-enable xdebug
  script:
    - ./vendor/bin/phpunit --coverage-text --coverage-cobertura=coverage.cobertura.xml
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
  needs: [ "build" ]
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: app/coverage.cobertura.xml
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - changes:
        - app/modules/**
        - app/src/**
        - app/tests/**

deploy:
  stage: deploy
  script:
    - echo "Deploying to production server"
  only:
    - master


pages:
  # Build mkdocs with python
  stage: deploy
  image: squidfunk/mkdocs-material:9.5.10
  before_script:
    - pip install markdown-callouts
  script:
    - mkdocs build -d public
  artifacts:
    paths:
      - public
