image: php:8.3

cache:
  paths:
    - vendor/
    - node_modules/

variables:
  SYMFONY_DEPRECATIONS_HELPER: weak

before_script:
  - cd app
  - apt-get update
  - apt-get install -y unzip
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  - composer install --no-interaction

stages:
  - qa
  - test
  - deploy

qa-ecs:
  stage: qa
  script:
    - ./bin/ecs check src
  changes:
    - modules/**
    - src/**

qa-rector:
  stage: qa
  script:
    - ./bin/rector process src
  changes:
    - modules/**
    - src/**

qa-phpstan:
  stage: qa
  script:
    - ./bin/phpstan analyse src
  changes:
    - modules/**
    - src/**

test:
  stage: test
  variables:
    XDEBUG_MODE: coverage
    DATABASE_URL: 'sqlite:///%kernel.project_dir%/var/data.db'
  before_script:
    - apt-get update
    - apt-get install -y sqlite3
    - pecl install xdebug && docker-php-ext-enable xdebug
  script:
    - ./bin/phpunit --coverage-text --coverage-cobertura=coverage.cobertura.xml
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.cobertura.xml
  rules:
    - changes:
        - modules/**
        - src/**
        - tests/**

deploy:
  stage: deploy
  script:
    - echo "Deploying to production server"
  only:
    - master

