home:
    path: /{path?}
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: base.html.twig
    requirements:
        path: ".+"

controllers:
    resource:
        path: ../src/User/Controller/
        namespace: App\User\Controller
    type: attribute
