/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AdminImport } from './routes/admin'
import { Route as FrontImport } from './routes/_front'
import { Route as FrontAuthLoginImport } from './routes/_front/auth/login'

// Create Virtual Routes

const AdminIndexLazyImport = createFileRoute('/admin/')()
const FrontIndexLazyImport = createFileRoute('/_front/')()

// Create/Update Routes

const AdminRoute = AdminImport.update({
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const FrontRoute = FrontImport.update({
  id: '/_front',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexLazyRoute = AdminIndexLazyImport.update({
  path: '/',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin/index.lazy').then((d) => d.Route))

const FrontIndexLazyRoute = FrontIndexLazyImport.update({
  path: '/',
  getParentRoute: () => FrontRoute,
} as any).lazy(() => import('./routes/_front/index.lazy').then((d) => d.Route))

const FrontAuthLoginRoute = FrontAuthLoginImport.update({
  path: '/auth/login',
  getParentRoute: () => FrontRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_front': {
      preLoaderRoute: typeof FrontImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/_front/': {
      preLoaderRoute: typeof FrontIndexLazyImport
      parentRoute: typeof FrontImport
    }
    '/admin/': {
      preLoaderRoute: typeof AdminIndexLazyImport
      parentRoute: typeof AdminImport
    }
    '/_front/auth/login': {
      preLoaderRoute: typeof FrontAuthLoginImport
      parentRoute: typeof FrontImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  FrontRoute.addChildren([FrontIndexLazyRoute, FrontAuthLoginRoute]),
  AdminRoute.addChildren([AdminIndexLazyRoute]),
])

/* prettier-ignore-end */
