<?php

declare(strict_types=1);

namespace App\Entity;

use ApiPlatform\Metadata\ApiProperty;
use ApiPlatform\Metadata\ApiResource;
use Doctrine\ORM\Mapping as ORM;

/**
 * A Report generated by governmental or non-governmental organization.
 *
 * @see https://schema.org/Report
 */
#[ORM\Entity]
#[ApiResource(types: ['https://schema.org/Report'])]
class Report extends Article
{
    /**
     * The number or other unique designator assigned to a Report by the publishing organization.
     *
     * @see https://schema.org/reportNumber
     */
    #[ORM\OneToOne(targetEntity: 'App\Entity\Text')]
    #[ApiProperty(types: ['https://schema.org/reportNumber'])]
    private ?string $reportNumber = null;

    public function setReportNumber(?string $reportNumber): void
    {
        $this->reportNumber = $reportNumber;
    }

    public function getReportNumber(): ?string
    {
        return $this->reportNumber;
    }
}
