name: Symfony

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  #  check-dockerfiles:
  #    name: Check Dockerfile
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: Checkout
  #        uses: actions/checkout@v3
  #
  #      - name: Check php/Dockerfile
  #        uses: hadolint/hadolint-action@v3.1.0
  #        with:
  #          dockerfile: .docker/php/Dockerfile
  #
  #      - name: Check php/Dockerfile
  #        uses: hadolint/hadolint-action@v3.1.0
  #        with:
  #          dockerfile: .docker/mkdocs/Dockerfile

  run-ecs:
    name: Run ECS
    runs-on: ubuntu-latest
    steps:
      - name: list env
        run: env
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: castor
      - name: Install ECS
        run: cd $GITHUB_ACTION_PATH/tools/ecs && composer install
      - name: Run ECS
        run: cd $GITHUB_ACTION_PATH/tools/ecs && $GITHUB_ACTION_PATH/tools/ecs/vendor/bin/ecs check --config $GITHUB_ACTION_PATH/app/ecs.php

  run-rector:
    name: Run Rector
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: castor
      - name: Install Rector
        run: cd $GITHUB_ACTION_PATH/tools/rector && composer install
      - name: Run Rector
        run: cd $GITHUB_ACTION_PATH/tools/rector && $GITHUB_ACTION_PATH/tools/rector/vendor/bin/rector process --config $GITHUB_ACTION_PATH/app/rector.php

  run-phpstan:
    name: Run PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: castor
      - name: Install PHPStan
        run: cd $GITHUB_ACTION_PATH/tools/phpstan && composer install
      - name: Run PHPStan
        run: cd $GITHUB_ACTION_PATH/tools/phpstan && $GITHUB_ACTION_PATH/tools/phpstan/vendor/bin/phpstan analyse --level=8 --configuration $GITHUB_ACTION_PATH/app/phpstan.neon --memory-limit=1G

  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: castor
      - name: Install App
        run: cd $GITHUB_ACTION_PATH/app && composer install
      - name: Run Tests
        run: cd $GITHUB_ACTION_PATH/app && $GITHUB_ACTION_PATH/vendor/bin/phpunit
