name: Symfony

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  #  check-dockerfiles:
  #    name: Check Dockerfile
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: Checkout
  #        uses: actions/checkout@v3
  #
  #      - name: Check php/Dockerfile
  #        uses: hadolint/hadolint-action@v3.1.0
  #        with:
  #          dockerfile: .docker/php/Dockerfile
  #
  #      - name: Check php/Dockerfile
  #        uses: hadolint/hadolint-action@v3.1.0
  #        with:
  #          dockerfile: .docker/mkdocs/Dockerfile

  install-app:
    name: Install App Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: castor
      - name: Install Composer
        run: cd ./app && composer install
      - name: Cache App Vendor
        uses: actions/cache@v2
        with:
          path: ./app/vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('app/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-app-

  install-tools:
    name: Install Tools
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: castor
      - name: Install Tools
        run: |
          for dir in tools/*; do
              if [ -f "$dir/composer.json" ]; then
              cd $dir
              composer install
              cd ../..
              fi
          done
      - name: Cache Tools
        uses: actions/cache@v2
        with:
          path: ./tools
          key: ${{ runner.os }}-composer-${{ hashFiles('tools/**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-tools-

  run-ecs:
    name: Run ECS
    runs-on: ubuntu-latest
    needs: install-tools
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: castor
      - name: Restore Tools Vendor
        uses: actions/cache@v2
        with:
          path: ./tools
          key: ${{ runner.os }}-composer-${{ hashFiles('tools/**/composer.lock') }}
      - name: Run ECS
        run: cd tools/ecs && ./vendor/bin/ecs check

  run-rector:
    name: Run Rector
    runs-on: ubuntu-latest
    needs: install-tools
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: castor
      - name: Restore Tools Vendor
        uses: actions/cache@v2
        with:
          path: ./tools
          key: ${{ runner.os }}-composer-${{ hashFiles('tools/**/composer.lock') }}
      - name: Run Rector
        run: cd tools/rector && ./vendor/bin/rector process

  run-phpstan:
    name: Run PHPStan
    runs-on: ubuntu-latest
    needs: install-tools
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: castor
      - name: Restore Tools Vendor
        uses: actions/cache@v2
        with:
          path: ./tools
          key: ${{ runner.os }}-composer-${{ hashFiles('tools/**/composer.lock') }}
      - name: Run PHPStan
        run: cd tools/phpstan && ./vendor/bin/phpstan analyse

  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: install-app
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: castor
      - name: Restore App Vendor
        uses: actions/cache@v2
        with:
          path: ./app/vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('app/composer.lock') }}
      - name: Run Tests
        run: vendor/bin/phpunit