name: Symfony

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  #  check-dockerfiles:
  #    name: Check Dockerfile
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: Checkout
  #        uses: actions/checkout@v3
  #
  #      - name: Check php/Dockerfile
  #        uses: hadolint/hadolint-action@v3.1.0
  #        with:
  #          dockerfile: .docker/php/Dockerfile
  #
  #      - name: Check php/Dockerfile
  #        uses: hadolint/hadolint-action@v3.1.0
  #        with:
  #          dockerfile: .docker/mkdocs/Dockerfile

  run-ecs:
    name: Run ECS
    runs-on: ubuntu-latest
    needs: install-tools
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: castor
      - name: Install ECS
        run: cd ./tools/ecs && composer install
      - name: Run ECS
        run: cd ./tools/ecs && ./vendor/bin/ecs check src

  run-rector:
    name: Run Rector
    runs-on: ubuntu-latest
    needs: install-tools
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: castor
      - name: Install Rector
        run: cd ./tools/rector && composer install
      - name: Run Rector
        run: cd ./tools/rector && ./vendor/bin/rector process

  run-phpstan:
    name: Run PHPStan
    runs-on: ubuntu-latest
    needs: install-tools
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: castor
      - name: Install PHPStan
        run: cd ./tools/phpstan && composer install
      - name: Run PHPStan
        run: cd ./tools/phpstan && ./vendor/bin/phpstan analyse

  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: install-app
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: castor
      - name: Install App
        run: cd ./app && composer install
      - name: Run Tests
        run: cd ./app && ./vendor/bin/phpunit
