name: Symfony

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  #  check-dockerfiles:
  #    name: Check Dockerfile
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: Checkout
  #        uses: actions/checkout@v3
  #
  #      - name: Check php/Dockerfile
  #        uses: hadolint/hadolint-action@v3.1.0
  #        with:
  #          dockerfile: .docker/php/Dockerfile
  #
  #      - name: Check php/Dockerfile
  #        uses: hadolint/hadolint-action@v3.1.0
  #        with:
  #          dockerfile: .docker/mkdocs/Dockerfile

  install-app:
    name: Install App Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: castor
      - name: Install Composer
        run: cd ./app && composer install
      - name: Cache Composer
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

  install-tools:
    name: Install Tools
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: castor
      - name: Install Tools
        run: |
          for dir in tools/*; do
              if [ -f "$dir/composer.json" ]; then
              cd $dir
              composer install
              cd ../..
              fi
          done
      - name: Cache Tools
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('tools/**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

  common-tools-run: &common-tools-run
    runs-on: ubuntu-latest
    needs: install-tools
    steps: &common-tools-run-steps
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: castor

  run-ecs:
    name: Run ECS
    <<: *common-tools-run
    steps:
      - name: Run ECS
        run: vendor/bin/ecs check src

  run-rector:
    name: Run Rector
    <<: *common-tools-run
    steps:
      - name: Run Rector
        run: vendor/bin/rector process src

  run-phpstan:
    name: Run PHPStan
    <<: *common-tools-run
    steps:
      - name: Run PHPStan
        run: vendor/bin/phpstan analyse src

  common-app-run: &common-app-run
    runs-on: ubuntu-latest
    needs: install-app
    steps: &common-app-run-steps
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: castor

  run-tests:
    name: Run Tests
    <<: *common-app-run
    steps:
      - name: Run Tests
        run: cd ./app && vendor/bin/phpunit

